# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c670f21b24197a76ad3ebad5bebb06327830854593ed27f55bbc351c7e100a5ade654316544cec0698f9c6724a730d0b69ffa36097c42b6de9b311ece5f15b47

test:
  secret_key_base: 5a0ec044852a395298fced4ee31dee18e80914a42f8d5f5f591f597104e8fe05f063fd4921f1b968019bd50ed7a7c2b77c9442d9e348dbb598eee9030187efbb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
